pull_request_rules:
  - name: Request review from team
    description: Request review from a specific team when checks are green.
    conditions:
      - 'closed'
      - '#approved-reviews-by=1'
      - '#changes-requested-reviews-by=1'
    actions:
      request_reviews:
        users:
          - Shayera
          - adruga-h1
          
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - '#approved-reviews-by>=1'
      - check-success=CI
    actions:
      queue:
        name: default

  - name: add a label with the name of the branch
    conditions:
    actions:
      label:
        add:
          - "branch:{{base}}"
